# Generated by Django 4.2.10 on 2024-02-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_brandmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='usecase',
            field=models.CharField(choices=[('LONG_DISTANCE', 'Long Distance'), ('COMMERCIAL', 'Commercial'), ('SPORTS_CAR', 'Sports Cars'), ('SHORT_DISTANCE', 'Short Distance'), ('COLLECTORS_ITEM', 'Collectors Item')], default='SHORT_DISTANCE', max_length=20),
        ),
    ]
