# Generated by Django 4.2.10 on 2024-02-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carmodel_usecase'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='fuel_type',
            field=models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('HYBRID', 'Hybrid'), ('ELETRIC', 'Electric')], default='PETROL', max_length=7),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='year',
            field=models.PositiveSmallIntegerField(default=2017),
        ),
    ]
